name: Pull Request Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Lint Customer Portal
      run: npm run lint --workspace=@logitrack/customer-portal
      
    - name: Lint Backend
      run: npm run lint --workspace=@logitrack/backend
      continue-on-error: true  # Since backend lint isn't set up yet
    
    - name: Build
      run: npm run build --workspaces --if-present
    
    - name: Test
      run: npm run test --workspaces --if-present